### ISSUE TITLE
[Feature request] Add support for Power Consumption (emeter) on HS110

### ISSUE THREAD

**Issue by osos** [biddster/node-red-contrib-hs100#1]
Thx for the works.

Could you add support for some of the other features of HS1x0, like emeter / power consumption readouts?

**Comment by biddster** [comment]
I'm sure that's possible. I don't actually own one, I wrote this blind for a friend. 

How would you like those metrics exposed?

**Comment by biddster** [comment]
I've just had a look at https://github.com/czjs2/hs100-api and it seems we could call `plug.getConsumption` and emit the data from that in the msg.payload. 

I could expose it via an input topic/payload of the string 'consumption' and you could request it at whatever frequency you require.

Would that do?

**Comment by biddster** [comment]
0.3.0 is released with power consumption exposed. I've not been able to test it so please report back and let me know.

**Comment by st3inar** [comment]
Readout for power consumption data is working fine on my HS110. Thank you!
