### ISSUE TITLE
Add support for state

### ISSUE THREAD

**Issue by st3inar** [biddster/node-red-contrib-hs100#3]
Would have been nice to get the state of the a HS100/HS110, I need it to update the UI if the switch has been controlled from the native app on my phone. getPowerState from the https://github.com/czjs2/hs100-api should do. Maybe the getStatus aswell, but that is just out of curiosity.

Good work!

**Comment by biddster** [comment]
I may as well add support for all the other actuations like getSysInfo whilst I'm there.

**Comment by biddster** [comment]
Fixed on 0.4.0 @st3inar. Please give it a test as I don't actually own one of these plugs. Reopen this issue if you have any problems.

**Comment by martinschki** [comment]
i was trying to get some kind of output from the node on the output to feed back into my UI, but nothing..
have upgraded to 0.4.0
