### ISSUE TITLE
Readme information - Model numbers and features

### ISSUE THREAD

**Issue by whatsupskip** [biddster/node-red-contrib-hs100#6]
Thank you for your work on this module.

Just a few things that need to be modified regarding the models and the features/commands available. The HS100 is a simple switch and does not support consumption. The HS110 includes the power consumption feature.

I have tested this module on the Australian version of the HS110. Thus far it all seems to be working.

**Comment by biddster** [comment]
Many thanks for the report.

**Comment by biddster** [comment]
Fixed in 0.4.1
